name: Build Flutter App

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setting up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.29.0

      - name: Flutter Version
        run: flutter --version

      - name: Cleaning Project
        run: flutter clean

      - name: Installing Dependencies
        run: flutter pub get

      - name: Build APK (Split per ABI)
        run: flutter build apk --split-per-abi

      - name: Create GitHub Release and Upload APKs
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          name: "Release v1.0.0"
          artifacts: build/app/outputs/flutter-apk/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
