name: Build Flutter App

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setting up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter Version
        run: flutter --version

      - name: Cleaning Project
        run: flutter clean

      - name: Installing Dependencies
        run: flutter pub get

      - name: Build APK (Split per ABI)
        run: flutter build apk --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: build/app/outputs/flutter-apk/*.apk
